### ISSUE TITLE
pre-commit installation will fail with Python 3.11

### ISSUE THREAD

**Issue by fbpnz** [par-tec/python-cookiecutter#14]
Using the command "pre-commit run --all-files" in a environment with Python 3.11 will fail during the installation phase.

Here I attached the pre-commit log.
[pre-commit.log](https://github.com/par-tec/python-cookiecutter/files/10792881/pre-commit.log)

**Comment by ioggstream** [comment]
Great work @fbpnz ! Instead of attaching the log, You can just paste the problematic snippet.
